name: Build Docker and Push

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  docker-build:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build and push
        uses: ./.github/actions/docker-build
        if: ${{ github.event_name == 'workflow_dispatch' || env.DOCKER_BUILD == 'true' }}
        with:
          NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
          SERVICE_NAME: openg2p-spar-self-service-api
          DOCKERFILE_PATH: Dockerfile
          DOCKER_HUB_TOKEN: ${{ secrets.docker_hub_token }}
          DOCKER_HUB_ACTOR: ${{ secrets.docker_hub_actor }}
